export const EscrowABI = [
  {
    type: "function",
    name: "createJob",
    stateMutability: "nonpayable",
    inputs: [
      { name: "freelancer", type: "address" },
      { name: "title", type: "string" },
      { name: "milestone_descriptions", type: "string[]" },
      { name: "milestone_amounts", type: "uint256[]" },
      { name: "duration_seconds", type: "uint64" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "acceptJob",
    stateMutability: "nonpayable",
    inputs: [{ name: "job_id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "initialize",
    stateMutability: "nonpayable",
    inputs: [
      { name: "usdc_token", type: "address" },
      { name: "gtl_token", type: "address" },
      { name: "fee_recipient", type: "address" },
      { name: "ai_oracle", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "fundJob",
    stateMutability: "nonpayable",
    inputs: [{ name: "job_id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "deliverMilestone",
    stateMutability: "nonpayable",
    inputs: [
      { name: "job_id", type: "uint256" },
      { name: "milestone_id", type: "uint256" },
      { name: "delivery_hash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "releaseMilestone",
    stateMutability: "nonpayable",
    inputs: [
      { name: "job_id", type: "uint256" },
      { name: "milestone_id", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "raiseDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "job_id", type: "uint256" },
      { name: "milestone_id", type: "uint256" },
      { name: "reason", type: "string" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "proposeSettlement",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dispute_id", type: "uint256" },
      { name: "client_bps", type: "uint16" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitAiReport",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dispute_id", type: "uint256" },
      { name: "report_hash", type: "bytes32" },
      { name: "confidence", type: "uint8" },
      { name: "suggested_client_bps", type: "uint16" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptAiSettlement",
    stateMutability: "nonpayable",
    inputs: [{ name: "dispute_id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "registerJuror",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "stake",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "unstake",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "escalateToJury",
    stateMutability: "nonpayable",
    inputs: [{ name: "dispute_id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "assignJurors",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dispute_id", type: "uint256" },
      { name: "jurors", type: "address[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "commitVote",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dispute_id", type: "uint256" },
      { name: "commitment", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "revealVote",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dispute_id", type: "uint256" },
      { name: "client_bps", type: "uint16" },
      { name: "freelancer_bps", type: "uint16" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeJury",
    stateMutability: "nonpayable",
    inputs: [{ name: "dispute_id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "forceTimeout",
    stateMutability: "nonpayable",
    inputs: [{ name: "dispute_id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getJobCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getJobBasic",
    stateMutability: "view",
    inputs: [{ name: "job_id", type: "uint256" }],
    outputs: [
      { type: "address" },
      { type: "address" },
      { type: "string" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint8" },
      { type: "uint64" },
      { type: "uint64" },
      { type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "getMilestone",
    stateMutability: "view",
    inputs: [
      { name: "job_id", type: "uint256" },
      { name: "milestone_id", type: "uint256" },
    ],
    outputs: [
      { type: "string" },
      { type: "uint256" },
      { type: "bool" },
      { type: "bool" },
      { type: "bool" },
      { type: "bool" },
      { type: "uint256" },
      { type: "bytes32" },
      { type: "uint64" },
      { type: "uint64" },
    ],
  },
];
