/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IEscrowContract {
    function createJob(address freelancer, string calldata title, string[] memory milestone_descriptions, uint256[] memory milestone_amounts, uint64 duration_seconds) external returns (uint256);

    function acceptJob(uint256 job_id) external;

    function initialize(address usdc_token, address gtl_token, address fee_recipient, address ai_oracle) external;

    function fundJob(uint256 job_id) external;

    function deliverMilestone(uint256 job_id, uint256 milestone_id, bytes32 delivery_hash) external;

    function releaseMilestone(uint256 job_id, uint256 milestone_id) external;

    function raiseDispute(uint256 job_id, uint256 milestone_id, string calldata reason) external returns (uint256);

    function proposeSettlement(uint256 dispute_id, uint16 client_bps) external;

    function submitAiReport(uint256 dispute_id, bytes32 report_hash, uint8 confidence, uint16 suggested_client_bps) external;

    function acceptAiSettlement(uint256 dispute_id) external;

    function registerJuror() external;

    function stake(uint256 amount) external;

    function unstake(uint256 amount) external;

    function escalateToJury(uint256 dispute_id) external;

    function assignJurors(uint256 dispute_id, address[] memory jurors) external;

    function commitVote(uint256 dispute_id, bytes32 commitment) external;

    function revealVote(uint256 dispute_id, uint16 client_bps, uint16 freelancer_bps, bytes32 salt) external;

    function finalizeJury(uint256 dispute_id) external;

    function forceTimeout(uint256 dispute_id) external;

    function getJobCount() external view returns (uint256);

    function getJobBasic(uint256 job_id) external view returns (address, address, string memory, uint256, uint256, uint8, uint64, uint64, uint64);

    function getMilestone(uint256 job_id, uint256 milestone_id) external view returns (string memory, uint256, bool, bool, bool, bool, uint256, bytes32, uint64, uint64);

    error Unauthorized();

    error InvalidAddress();

    error InvalidJob();

    error InvalidMilestone();

    error InvalidAmount();

    error InvalidState();

    error AlreadyFunded();

    error AlreadyReleased();

    error AlreadyDelivered();

    error AlreadyRegistered();

    error JobNotFound();

    error MilestoneNotFound();

    error NotJobParty();

    error DisputeAlreadyExists();

    error DisputeNotFound();

    error DisputeStageMismatch();

    error InvalidBps();

    error AlreadyProposed();

    error AlreadyAcceptedAi();

    error CommitWindowClosed();

    error RevealWindowNotOpen();

    error RevealWindowClosed();

    error CommitmentMismatch();

    error AlreadyCommitted();

    error AlreadyRevealed();

    error DeadlockNotReached();

    error VotingClosed();

    error VotingNotStarted();

    error JurorNotEligible();

    error InsufficientStake();

    error ArithmeticOverflow();

    error JurorAlreadyActive();

    error JurorNotRegistered();
}
