export const EscrowABI = [
  {
    type: "function",
    name: "createJob",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_freelancer", type: "address" },
      { name: "_title", type: "string" },
      { name: "_milestoneDescriptions", type: "string[]" },
      { name: "_milestoneAmounts", type: "uint256[]" },
      { name: "_durationSeconds", type: "uint256" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "acceptJob",
    stateMutability: "nonpayable",
    inputs: [{ name: "jobId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "fundJob",
    stateMutability: "nonpayable",
    inputs: [{ name: "jobId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "markDelivered",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "uint256" },
      { name: "milestoneIndex", type: "uint256" },
      { name: "ipfsHash", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "releaseMilestone",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "uint256" },
      { name: "milestoneIndex", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "refundClient",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "uint256" },
      { name: "milestoneIndex", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "autoRelease",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "uint256" },
      { name: "milestoneIndex", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "raiseDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "uint256" },
      { name: "milestoneIndex", type: "uint256" },
      { name: "reason", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "uint256" },
      { name: "milestoneIndex", type: "uint256" },
      { name: "clientBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "agreeToSplit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "jobId", type: "uint256" },
      { name: "milestoneIndex", type: "uint256" },
      { name: "clientBps", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "jobCounter",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getJob",
    stateMutability: "view",
    inputs: [{ name: "jobId", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "client", type: "address" },
      { name: "freelancer", type: "address" },
      { name: "totalAmount", type: "uint256" },
      { name: "releasedAmount", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "title", type: "string" },
      { name: "createdAt", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getMilestone",
    stateMutability: "view",
    inputs: [
      { name: "jobId", type: "uint256" },
      { name: "milestoneIndex", type: "uint256" },
    ],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "description", type: "string" },
          { name: "amount", type: "uint256" },
          { name: "delivered", type: "bool" },
          { name: "released", type: "bool" },
          { name: "late", type: "bool" },
          { name: "ipfsHash", type: "string" },
          { name: "deliveredAt", type: "uint256" },
          { name: "disputeDeadline", type: "uint256" },
          { name: "disputeStatus", type: "uint8" },
          { name: "disputeReason", type: "string" },
          { name: "clientProposalBps", type: "uint256" },
          { name: "freelancerProposalBps", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "event",
    name: "JobCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "jobId", type: "uint256" },
      { indexed: true, name: "client", type: "address" },
      { indexed: true, name: "freelancer", type: "address" },
      { indexed: false, name: "totalAmount", type: "uint256" },
      { indexed: false, name: "title", type: "string" },
    ],
  },
];