export const ReputationABI = [
  {
    type: "function",
    name: "init",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setEscrowFactory",
    stateMutability: "nonpayable",
    inputs: [{ name: "escrow", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "recordJobCompleted",
    stateMutability: "nonpayable",
    inputs: [
      { name: "client_addr", type: "address" },
      { name: "freelancer_addr", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recordLateDelivery",
    stateMutability: "nonpayable",
    inputs: [{ name: "freelancer_addr", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "recordGhosting",
    stateMutability: "nonpayable",
    inputs: [{ name: "freelancer_addr", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "recordDisputeRaised",
    stateMutability: "nonpayable",
    inputs: [
      { name: "client_addr", type: "address" },
      { name: "freelancer_addr", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recordDisputeResolved",
    stateMutability: "nonpayable",
    inputs: [
      { name: "client_addr", type: "address" },
      { name: "freelancer_addr", type: "address" },
      { name: "client_bps", type: "uint256" },
      { name: "resolution_type", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recordJurorVote",
    stateMutability: "nonpayable",
    inputs: [
      { name: "juror_addr", type: "address" },
      { name: "was_correct", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getClientScore",
    stateMutability: "view",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getFreelancerScore",
    stateMutability: "view",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getJurorScore",
    stateMutability: "view",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getClientPassport",
    stateMutability: "view",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getFreelancerPassport",
    stateMutability: "view",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getJurorPassport",
    stateMutability: "view",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "uint256" },
    ],
  },
];